Create SentinelSearch.php
TheAlgorithms/PHP pull request #124
Opened 2023-10-06 07:01 UTC by Abhishek-Pashte

Added **Sentinel Search algorithm** in Searches algorithms

2023-10-07 04:22 UTC, darwinz requested changes
Thank you for contributing.  Please add this algorithm to the [Directory](https://github.com/TheAlgorithms/PHP/blob/master/DIRECTORY.md) and add unit tests.  See [CONTRIBUTING](https://github.com/TheAlgorithms/PHP/blob/master/CONTRIBUTING.md) if you have any questions.

2023-10-07 06:49 UTC, Abhishek-Pashte commented
Required changes has been made

2023-10-09 04:21 UTC, Abhishek-Pashte commented
Required changes has been made. Pls review those changes

2023-10-11 19:51 UTC, darwinz commented
Thanks for making those changes.  Please fix the linting errors that came up in the code-style workflow checks.

2023-10-27 17:41 UTC, darwinz commented
@Abhishek-Pashte , looks like we still have some linting errors

2024-06-14 05:33 UTC, darwinz commented on Searches/SentinelSearch.php
> +    $lastElement = $list[$len-1];
```suggestion
    $lastElement = $list[$len - 1];
```

2024-06-14 05:34 UTC, darwinz commented on Searches/SentinelSearch.php
> +    if ($lastElement == $target)
```suggestion
    if ($lastElement == $target) 
```

2024-06-14 05:34 UTC, darwinz commented on Searches/SentinelSearch.php
> +    }
```suggestion
    }
```

2024-06-14 05:35 UTC, darwinz commented on Searches/SentinelSearch.php
> +
```suggestion

```

2024-06-14 05:36 UTC, darwinz commented on Searches/SentinelSearch.php
> +    }
```suggestion
    $i = 0;

    //Traverse through array to search target
    while ($list[$i] != $target) 
    {
        $i++;
    }
```

2024-06-14 05:37 UTC, darwinz commented on Searches/SentinelSearch.php
> +?>
```suggestion
    if ($i < ($len - 1)) {
        return $i;
    }
    // Else element is not present return -1
    else {
        return -1;
    }
}
```

2024-06-14 05:41 UTC, darwinz commented on Searches/SentinelSearch.php
> +}
```suggestion
{
    //Length of array
    $len = sizeof($list);

    //Store last element of array
    $lastElement = $list[$len - 1];

    //Put target at the last position of array known as 'Sentinel'
    if ($lastElement == $target) {
        return ($len - 1);
    }
    //Put target at last index of array
    $list[$len - 1] = $target;

    //Initialize variable to traverse through array
    $i = 0;

    //Traverse through array to search target
    while ($list[$i] != $target) {
        $i++;
    }
    //Put last element at it's position
    $list[$len - 1] = $lastElement;

    //If i in less than length, It means element is present in array
    if ($i < ($len - 1)) {
        return $i;
    } else {
        return -1;
    }
}
```

2024-06-14 05:42 UTC, darwinz approved these changes
Thanks!

2024-06-14 05:42 UTC, merged