Create BaseX.php
TheAlgorithms/PHP pull request #140
Opened 2023-10-20 13:35 UTC by Sevada797

This function let's you calculate base X of any number <11

2023-10-24 05:48 UTC, darwinz requested changes
Thanks for wanting to contribute.  Please read the contributing guide for making contributions to this repo found at [CONTRIBUTING.md](https://github.com/TheAlgorithms/PHP/blob/master/CONTRIBUTING.md)

2023-10-25 00:12 UTC, Sevada797 commented
Hi @darwinz thanks for checking my commit, I have read the file [CONTRIBUTING.md](https://github.com/TheAlgorithms/PHP/blob/master/CONTRIBUTING.md), I think everything is OK, if possible please tell me what exact changes should I make.

2023-10-27 17:45 UTC, darwinz commented
Please follow modern PHP style guide rules.  We generally stick to the guidelines in the [PSR-12 style guide](https://xoops.gitbook.io/xoops-modules-cookbook/coding-standards/standards/styleguide).  Code should be in a class with a function that defines the algorithm.  You also need to add unit tests.  Format your code so that it's readable and maintainable using the PSR-12 style guide.  Thanks!

2023-11-29 02:53 UTC, Sevada797 commented
> Please follow modern PHP style guide rules. We generally stick to the guidelines in the [PSR-12 style guide](https://xoops.gitbook.io/xoops-modules-cookbook/coding-standards/standards/styleguide). Code should be in a class or function that defines the algorithm. You also need to add unit tests. Format your code so that it's readable and maintainable using the PSR-12 style guide. Thanks!

I've done it, can you please check it, sorry for the long delay.

2023-11-30 06:29 UTC, darwinz commented on DIRECTORY.md
> +  * [BaseX](./BaseX.php)
```suggestion
  * [BaseX](./Maths/BaseX.php)
```

2023-11-30 06:30 UTC, darwinz reviewed
This looks so much better.  Thanks for updating!  Please see one small change I requested, and also please add a unit test for this algorithm.  Thanks!

2023-12-12 05:11 UTC, Sevada797 commented
Hi @darwinz, can you see if everything is okay now please?

2023-12-12 06:52 UTC, darwinz approved these changes

2023-12-12 06:55 UTC, darwinz commented on tests/Maths/MathsTest.php
> +}
```suggestion
    public function testBaseX() 
    {
        $this->assertEquals(11, baseX(3, 2));
        $this->assertEquals(22, baseX(8, 3));   
        $this->assertEquals(21, baseX(15, 7));
        $this->assertEquals(20, baseX(16, 8));
    }
```

2023-12-12 06:57 UTC, darwinz requested changes
Approved on accident.  There are still some formatting issues.  One way to check before committing is to run

```
vendor/bin/phpcs -n
```

2023-12-13 06:21 UTC, darwinz commented on tests/Maths/MathsTest.php
> +    public function testBaseX()
```suggestion
    public function testBaseX()
```

2023-12-13 06:21 UTC, darwinz commented on tests/Maths/MathsTest.php
> +        $this->assertEquals(22, baseX(8, 3));
```suggestion
        $this->assertEquals(22, baseX(8, 3));
```

2023-12-13 17:29 UTC, darwinz approved these changes
Thank you!

2023-12-13 17:30 UTC, merged