Implemented Disjoint Set (Union-Find) Data Structure
TheAlgorithms/PHP pull request #160
Opened 2024-08-24 19:26 UTC by Ramy-Badr-Ahmed

**Contents:**

- `DisjointSetNode` Class: Represents individual nodes with `data`, `rank`, and `parent` attributes.

- DisjointSet Class: Implements core methods:

    `findSet`: Utilizes path compression for representative lookup.
    `unionSet`: Applies union by rank to manage the merging of sets.

- `Unit Tests`: Tests using PHPUnit to validate the correct behavior of the Disjoint Set structure. The tests cover different numbers of nodes and sets.

**Compatibility**: 
The implementation supports PHP 7.4 and above by omitting the `mixed` type hint, otherwise PHP 8.0^ is supported directly.

2024-09-03 09:14 UTC, Ramy-Badr-Ahmed commented
@darwinz 
Looking forward for your review :-)

2024-09-03 09:15 UTC, Ramy-Badr-Ahmed commented
@darwinz 
Looking forward for your review :-)

2024-09-08 12:09 UTC, Md-Kasali commented
Move your DisjointSetTest.php file under tests/DataStructures/ directory

2024-09-08 12:12 UTC, Md-Kasali commented
Move your DisjointSetTest.php file under the DataStructures/ directory into the tests/DataStructures directory. The test files are organized under the tests/ directory.

2024-09-08 14:57 UTC, Ramy-Badr-Ahmed reviewed
Moved `DisjointSetTest.php` to  `tests/DataStructures`

2024-09-11 05:08 UTC, darwinz commented on DataStructures/DisjointSets/DisjointSetNode.php
> +    public function __construct(mixed $data = NULL) {
```suggestion
    public function __construct(mixed $data = NULL) 
    {
```

2024-09-11 05:09 UTC, darwinz commented on DataStructures/DisjointSets/DisjointSetNode.php
> +}
```suggestion
}

```

2024-09-11 05:09 UTC, darwinz commented on DataStructures/DisjointSets/DisjointSet.php
> +}
```suggestion
}

```

2024-09-11 05:10 UTC, darwinz commented on tests/DataStructures/DisjointSetTest.php
> +    }
```suggestion
    }
```

2024-09-11 05:11 UTC, darwinz commented on tests/DataStructures/DisjointSetTest.php
> +                return true;
```suggestion
            if (in_array($i, $set) && in_array($j, $set)) {
                return true;
            }    
```

2024-09-11 05:11 UTC, darwinz commented on tests/DataStructures/DisjointSetTest.php
> +}
```suggestion
}

```

2024-09-11 05:13 UTC, darwinz requested changes
This is great, thanks for the contribution!

There are a few small linting issues, found by the GitHub Actions linter we use in this repo.  You can also run PHPCBF to automatically fix these types of issues in the future.

2024-09-11 05:17 UTC, darwinz commented
PHPUnit is also failing, so you'll want to fix that error as well.

```
1) DataStructures\DisjointSetTest::testFindSet
Error: Class 'DisjointSet' not found

/home/runner/work/PHP/PHP/tests/DataStructures/DisjointSetTest.php:16
phpvfscomposer:///home/runner/work/PHP/PHP/vendor/phpunit/phpunit/phpunit:106
```

2024-09-11 11:47 UTC, Ramy-Badr-Ahmed commented
> This is great, thanks for the contribution!
> 
> There are a few small linting issues, found by the GitHub Actions linter we use in this repo. You can also run PHPCBF to automatically fix these types of issues in the future.

Thanks!
I have committed your changes and considered the rest of the PHPCP remarks.

2024-09-11 11:55 UTC, Ramy-Badr-Ahmed commented
> PHPUnit is also failing, so you'll want to fix that error as well.
> 
> ```
> 1) DataStructures\DisjointSetTest::testFindSet
> Error: Class 'DisjointSet' not found
> 
> /home/runner/work/PHP/PHP/tests/DataStructures/DisjointSetTest.php:16
> phpvfscomposer:///home/runner/work/PHP/PHP/vendor/phpunit/phpunit/phpunit:106
> ```

It works now with a corrected namespace and manual `requires` following the exisitng pattern 🙂

```php
Testing started at 13:48 ...
PHPUnit 9.6.20 by Sebastian Bergmann and contributors.

Time: 00:00.004, Memory: 4.00 MB

OK (1 test, 36 assertions)

Process finished with exit code 0
```

2024-09-11 15:41 UTC, darwinz commented
The test is still failing.  Please run your test locally and make sure it's passing.

2024-09-11 20:27 UTC, Ramy-Badr-Ahmed commented
Hi Brandon,

Thanks for the info. I have resolved the issues and Github actions have passed in my forked version. Can you please check it out again?

Thanks a lot for your time

Kind regards,
Ramy

From: Brandon Johnson ***@***.***>
Sent: 11 September 2024 17:42
To: TheAlgorithms/PHP ***@***.***>
Cc: Ramy ***@***.***>; Author ***@***.***>
Subject: Re: [TheAlgorithms/PHP] Implemented Disjoint Set (Union-Find) Data Structure (PR #160)


The test is still failing. Please run your test locally and make sure it's passing.

—
Reply to this email directly, view it on GitHub<https://github.com/TheAlgorithms/PHP/pull/160#issuecomment-2344024763>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6FSNI3WQWORCVGNAF2PYZTZWBQC3AVCNFSM6AAAAABNB2ZKE2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBUGAZDINZWGM>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2024-09-13 14:06 UTC, darwinz approved these changes

2024-09-13 14:06 UTC, darwinz commented
Thank you!

2024-09-13 14:06 UTC, merged