temperature conversions
TheAlgorithms/PHP pull request #169
Opened 2024-10-03 16:48 UTC by MaarcooC

Added 6 functions for temperature conversion between Celsius, Fahrenheit, and Kelvin with input validation.

2024-10-04 13:50 UTC, MaarcooC commented
added a function that checks if a number is perfect.

2024-10-07 06:04 UTC, darwinz requested changes
Thanks for submitting a PR!  Please add proper unit tests in the appropriate `tests` directory and location.  Also, your code needs to be linted and tests passing first, so please run PHPCS (`vendor/bin/phpcs -n`)

2024-10-07 16:11 UTC, MaarcooC commented
Sorry for that, I now added proper unit tests and ran phpcs.

2024-10-07 16:20 UTC, darwinz commented on tests/Conversions/ConversionsTest.php
> +}
```suggestion
}

```

2024-10-07 16:20 UTC, darwinz commented on tests/Conversions/ConversionsTest.php
> +}
This is a code style issue that the linter found

2024-10-07 16:53 UTC, MaarcooC reviewed
added unit tests and phpcs

2024-10-15 20:49 UTC, darwinz requested changes
Can you please fix the comments to be formatted as doc comments?  See [here](https://github.com/TheAlgorithms/PHP/blob/master/Sorting/BubbleSort2.php#L3C1-L10C4) for an example.

2024-10-19 07:02 UTC, darwinz approved these changes
Looks great.  Thank you!

2024-10-19 07:02 UTC, merged