Added Palindrome checker
TheAlgorithms/PHP pull request #85
Opened 2022-10-06 16:24 UTC by Samadmemon991

Palindromic number is a symmetrical number which remains same when the digits are reversed 
e.g. 121
For further details you can visit this [link.](https://en.wikipedia.org/wiki/Palindromic_number)

2022-10-07 08:15 UTC, darwinz approved these changes

2022-10-07 08:21 UTC, darwinz commented on Maths/CheckPalindrome.php
> +function isPalindrome(int $input): bool
This function name will need to be changed to a different name.  The same function name is declared in `Strings/CheckPalindrome.php`, so there's a collision when running the tests.  Maybe you could name it to `isPalindromic` or `isNumericPalindrome`.

2022-10-07 08:22 UTC, darwinz requested changes
Tests are failing due to a collision in the naming of the function `isPalindrome`, so that function name will need to be changed

2022-10-07 10:58 UTC, Samadmemon991 commented
@darwinz I have updated code kindly check it now and thanks for letting me know cause of failed tests

2022-10-09 06:51 UTC, darwinz approved these changes

2022-10-09 06:51 UTC, merged