Added BFS
TheAlgorithms/PHP pull request #98
Opened 2022-11-24 20:00 UTC by aryanshb

BFS along with tests; directory also updated.

2022-11-27 05:38 UTC, darwinz commented on tests/Graphs/BreadthFirstSearchTest.php
> +class DepthFirstSearchTest extends TestCase
```suggestion
class BreadthFirstSearchTest extends TestCase
```

2022-11-27 05:39 UTC, darwinz requested changes
Please update the name of the test class as suggested.  Thanks!

2022-11-27 19:28 UTC, aryanshb commented
I have made required changes, please check.

2022-11-29 07:20 UTC, darwinz approved these changes

2022-11-29 07:21 UTC, merged